syntax = "proto3";
package websocket;

option go_package = "gopkg.in/go-mixed/kratos-packages.v2/pkg/websocket/proto;proto";

import "google/protobuf/any.proto";


message WebsocketGrpcRequest {
  optional string message_id = 1;
  string service = 2;
  string method = 3;
  string type  = 4;

  google.protobuf.Any data = 5;
}


message WebsocketGrpcResponse {
  optional string message_id = 1;
  string service = 2;
  string method = 3;
  string type  = 4;
  google.protobuf.Any data = 5;

  int32 code = 10;
  string message = 11;
}