// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: pkg/websocket/proto/ws.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WebsocketGrpcRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     *string                `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3,oneof" json:"message_id,omitempty"`
	Service       string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	Method        string                 `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Data          *anypb.Any             `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebsocketGrpcRequest) Reset() {
	*x = WebsocketGrpcRequest{}
	mi := &file_pkg_websocket_proto_ws_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebsocketGrpcRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebsocketGrpcRequest) ProtoMessage() {}

func (x *WebsocketGrpcRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_websocket_proto_ws_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebsocketGrpcRequest.ProtoReflect.Descriptor instead.
func (*WebsocketGrpcRequest) Descriptor() ([]byte, []int) {
	return file_pkg_websocket_proto_ws_proto_rawDescGZIP(), []int{0}
}

func (x *WebsocketGrpcRequest) GetMessageId() string {
	if x != nil && x.MessageId != nil {
		return *x.MessageId
	}
	return ""
}

func (x *WebsocketGrpcRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *WebsocketGrpcRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *WebsocketGrpcRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *WebsocketGrpcRequest) GetData() *anypb.Any {
	if x != nil {
		return x.Data
	}
	return nil
}

type WebsocketGrpcResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     *string                `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3,oneof" json:"message_id,omitempty"`
	Service       string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	Method        string                 `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Data          *anypb.Any             `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	Code          int32                  `protobuf:"varint,10,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,11,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebsocketGrpcResponse) Reset() {
	*x = WebsocketGrpcResponse{}
	mi := &file_pkg_websocket_proto_ws_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebsocketGrpcResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebsocketGrpcResponse) ProtoMessage() {}

func (x *WebsocketGrpcResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_websocket_proto_ws_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebsocketGrpcResponse.ProtoReflect.Descriptor instead.
func (*WebsocketGrpcResponse) Descriptor() ([]byte, []int) {
	return file_pkg_websocket_proto_ws_proto_rawDescGZIP(), []int{1}
}

func (x *WebsocketGrpcResponse) GetMessageId() string {
	if x != nil && x.MessageId != nil {
		return *x.MessageId
	}
	return ""
}

func (x *WebsocketGrpcResponse) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *WebsocketGrpcResponse) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *WebsocketGrpcResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *WebsocketGrpcResponse) GetData() *anypb.Any {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *WebsocketGrpcResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *WebsocketGrpcResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_pkg_websocket_proto_ws_proto protoreflect.FileDescriptor

const file_pkg_websocket_proto_ws_proto_rawDesc = "" +
	"\n" +
	"\x1cpkg/websocket/proto/ws.proto\x12\twebsocket\x1a\x19google/protobuf/any.proto\"\xb9\x01\n" +
	"\x14WebsocketGrpcRequest\x12\"\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tH\x00R\tmessageId\x88\x01\x01\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12\x16\n" +
	"\x06method\x18\x03 \x01(\tR\x06method\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12(\n" +
	"\x04data\x18\x05 \x01(\v2\x14.google.protobuf.AnyR\x04dataB\r\n" +
	"\v_message_id\"\xe8\x01\n" +
	"\x15WebsocketGrpcResponse\x12\"\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tH\x00R\tmessageId\x88\x01\x01\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12\x16\n" +
	"\x06method\x18\x03 \x01(\tR\x06method\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12(\n" +
	"\x04data\x18\x05 \x01(\v2\x14.google.protobuf.AnyR\x04data\x12\x12\n" +
	"\x04code\x18\n" +
	" \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\v \x01(\tR\amessageB\r\n" +
	"\v_message_idB\x96\x01\n" +
	"\rcom.websocketB\aWsProtoP\x01Z8gopkg.in/go-mixed/kratos-packages.v2/pkg/websocket/proto\xa2\x02\x03WXX\xaa\x02\tWebsocket\xca\x02\tWebsocket\xe2\x02\x15Websocket\\GPBMetadata\xea\x02\tWebsocketb\x06proto3"

var (
	file_pkg_websocket_proto_ws_proto_rawDescOnce sync.Once
	file_pkg_websocket_proto_ws_proto_rawDescData []byte
)

func file_pkg_websocket_proto_ws_proto_rawDescGZIP() []byte {
	file_pkg_websocket_proto_ws_proto_rawDescOnce.Do(func() {
		file_pkg_websocket_proto_ws_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_websocket_proto_ws_proto_rawDesc), len(file_pkg_websocket_proto_ws_proto_rawDesc)))
	})
	return file_pkg_websocket_proto_ws_proto_rawDescData
}

var file_pkg_websocket_proto_ws_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_websocket_proto_ws_proto_goTypes = []any{
	(*WebsocketGrpcRequest)(nil),  // 0: websocket.WebsocketGrpcRequest
	(*WebsocketGrpcResponse)(nil), // 1: websocket.WebsocketGrpcResponse
	(*anypb.Any)(nil),             // 2: google.protobuf.Any
}
var file_pkg_websocket_proto_ws_proto_depIdxs = []int32{
	2, // 0: websocket.WebsocketGrpcRequest.data:type_name -> google.protobuf.Any
	2, // 1: websocket.WebsocketGrpcResponse.data:type_name -> google.protobuf.Any
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pkg_websocket_proto_ws_proto_init() }
func file_pkg_websocket_proto_ws_proto_init() {
	if File_pkg_websocket_proto_ws_proto != nil {
		return
	}
	file_pkg_websocket_proto_ws_proto_msgTypes[0].OneofWrappers = []any{}
	file_pkg_websocket_proto_ws_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_websocket_proto_ws_proto_rawDesc), len(file_pkg_websocket_proto_ws_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_websocket_proto_ws_proto_goTypes,
		DependencyIndexes: file_pkg_websocket_proto_ws_proto_depIdxs,
		MessageInfos:      file_pkg_websocket_proto_ws_proto_msgTypes,
	}.Build()
	File_pkg_websocket_proto_ws_proto = out.File
	file_pkg_websocket_proto_ws_proto_goTypes = nil
	file_pkg_websocket_proto_ws_proto_depIdxs = nil
}
