package awsSignature

import "github.com/pkg/errors"

var ErrUnsignedHeaders = errors.New("unsigned headers")
var ErrSignatureDoesNotMatch = errors.New("signature does not match")
var ErrRequestNotReadyYet = errors.New("request not ready yet")
var ErrExpiredPresignRequest = errors.New("expired presign request")
var ErrContentSHA256Mismatch = errors.New("content sha256 mismatch")
var ErrInvalidToken = errors.New("invalid token")
var ErrMissingDateHeader = errors.New("missing date header")
var ErrMalformedDate = errors.New("malformed date")
var ErrInvalidQuerySignatureAlgo = errors.New("invalid query signature algo")
var ErrMalformedPresignedDate = errors.New("malformed presigned date")
var ErrMalformedExpires = errors.New("malformed expires")
var ErrNegativeExpires = errors.New("negative expires")
var ErrMaximumExpires = errors.New("maximum expires")
var ErrAuthHeaderEmpty = errors.New("auth header empty")
var ErrSignatureVersionNotSupported = errors.New("signature version not supported")
var ErrMissingFields = errors.New("missing fields")
var ErrInvalidQueryParams = errors.New("invalid query params")
var ErrMissingSignHeadersTag = errors.New("missing sign headers tag")
var ErrMissingSignTag = errors.New("missing sign tag")
var ErrInvalidServiceName = errors.New("invalid service name")
var ErrInvalidRequestVersion = errors.New("invalid request version")
var ErrInvalidAccessKeyID = errors.New("invalid access key id")
var ErrMissingCredTag = errors.New("missing cred tag")
var ErrCredMalformed = errors.New("cred malformed")
var ErrMalformedCredentialDate = errors.New("malformed credential date")
var ErrInvalidRegion = errors.New("invalid region")
